### ISSUE TITLE
Use of ssl_context= keyword raises DeprecationWarnings

### ISSUE THREAD

**Issue by mrocklin** [tomplus/kubernetes_asyncio#59] opened 2019-02-01 20:21 UTC
I get the following deprecation warning when using this library.  

```python
lib/python3.6/site-packages/kubernetes_asyncio/client/rest.py:73: DeprecationWarning: ssl_context is deprecated, use ssl=context instead
    ssl_context=ssl_context
```

Swapping out `ssl_context=` for `ssl=` works fine when I apply the change locally.  However I'm not sure how best to enact change in this repository, given that parts (all?) of it is generated.  

cc @yuvipanda

**Comment by tomplus** [comment] 2019-02-01 22:05
Yes, this part is generated by swagger-codegen. Now I'm working on switching to the openapi-generator (#58). It's fixed there in the beta release so this warning will be removed eventually.

**Comment by tomplus** [comment] 2019-03-24 09:06
It's been fixed in the version v9.0.0.

**Comment by mrocklin** [comment] 2019-03-24 14:32
Thanks!

**Comment by mickours** [comment] 2020-02-06 14:14
The problem is still present in the current version (10.0.1):
```
kubernetes_asyncio/client/rest.py:69: DeprecationWarning: ssl_context is deprecated, use ssl=context instead
    ssl_context=ssl_context
```

**Comment by tomplus** [comment] 2020-02-06 14:26
@mickours could you check the version of aiohttp? The latest version of the library can print such warnings: https://github.com/tomplus/kubernetes_asyncio/issues/87 Thanks.

**Comment by mickours** [comment] 2020-02-06 15:49
Thanks for the quick answer!

I'm using aiohttp 3.5.4

It seems to come from this line:
https://github.com/tomplus/kubernetes_asyncio/blob/master/kubernetes_asyncio/client/rest.py#L69

**Comment by tomplus** [comment] 2020-02-06 15:57
Thanks, confirmed, reopen the issue.

**Comment by tomplus** [comment] 2020-02-26 23:44
It's fixed in the latest version of the library.

**Closed by tomplus** 2020-02-26 23:44 UTC

**Comment by mrocklin** [comment] 2020-02-27 03:32
I'm glad to hear it!  Thank you for tracking this @tomplus .

**Comment by mickours** [comment] 2020-02-27 20:31
Thanks a lot! 👍
