### ISSUE TITLE
watcher.stream call failed in pods

### ISSUE THREAD

**Issue by nikiladonya** [tomplus/kubernetes_asyncio#102] opened 2020-04-17 09:01 UTC
If i execute some code in pod of my cluster:
```
from kubernetes_asyncio import client
from kubernetes_asyncio import config
from kubernetes_asyncio import watch

config.load_incluster_config()
k8s_client = client.CoreV1Api()

watcher = watch.Watch()
async for event in watcher.stream(k8s_client.list_persistent_volume_claim_for_all_namespaces, timeout_seconds=5):
    pass
```

I see exception:
```
Traceback (most recent call last):
  File "t.py", line 22, in <module>
    asyncio.run(test())
  File "/usr/local/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "t.py", line 16, in test
    async for event in watcher.stream(
  File "/usr/local/lib/python3.8/site-packages/kubernetes_asyncio/watch/watch.py", line 114, in __anext__
    return await self.next()
  File "/usr/local/lib/python3.8/site-packages/kubernetes_asyncio/watch/watch.py", line 152, in next
    return self.unmarshal_event(line, self.return_type)
  File "/usr/local/lib/python3.8/site-packages/kubernetes_asyncio/watch/watch.py", line 90, in unmarshal_event
    js['object'] = self._api_client.deserialize(
  File "/usr/local/lib/python3.8/site-packages/kubernetes_asyncio/client/api_client.py", line 264, in deserialize
    return self.__deserialize(data, response_type)
  File "/usr/local/lib/python3.8/site-packages/kubernetes_asyncio/client/api_client.py", line 292, in __deserialize
    klass = getattr(kubernetes_asyncio.client.models, klass)
AttributeError: module 'kubernetes_asyncio.client.models' has no attribute ''
```
But if i load config by call `await config.load_kube_config()` and run script from cluster host, everything works

**Comment by tomplus** [comment] 2020-04-17 10:00
It looks like an error/exception is not properly handled by watch/stream - I'm checking it later.

Because it works externally I guess the RBAC blocks your query. Try to configure ClusterRole/Binding to allow such query (is usually denied by default). Please compare with this example https://github.com/tomplus/kubernetes_asyncio/blob/master/examples/in_cluster_config.py

**Comment by nikiladonya** [comment] 2020-04-17 10:41
@tomplus nope, RBAC is ok, i checked
but i have found fast solution - i created watcher with "return_type" kwarg:
```
watcher = watch.Watch(return_type='V1PersistentVolume')
async for event in watcher.stream(k8s_client.list_persistent_volume, timeout_seconds=3*Hour):
    pass
```
everything works

**Comment by tomplus** [comment] 2020-04-18 01:14
@nikiladonya I can't reproduce this issue. Your first example works for me from a pod too - proper return_type is calculated. The calculation use method doc strings so it shouldn't be dependent on a response or environment. Which version of K8s and the library do you have?
(In the second example you ask about list_persistent_volume not _claim).

**Comment by tomplus** [comment] 2020-06-06 22:57
I'm closing it. Please reopen if you still encounter this issue.

**Closed by tomplus** 2020-06-06 22:57 UTC
