### ISSUE TITLE
Don't try to close aiohttp connection pool inside `__del__`

### ISSUE THREAD

**Issue by WouldYouKindly** [tomplus/kubernetes_asyncio#91] opened 2020-01-15 15:08 UTC
Hi! Thanks for a great library. 

There is a flaw though: one really should not perform async cleanup inside `__del__`. This code may cause exceptions at shutdown: https://github.com/tomplus/kubernetes_asyncio/blob/master/kubernetes_asyncio/client/rest.py#L84

This is because `__del__` may be called after the event loop is closed.

The preferred way is to use an async context manager or add an API to explicitly shutdown the client. Example may be found here: https://stackoverflow.com/questions/54770360/how-can-i-wait-for-an-objects-del-to-finish-before-the-async-loop-closes

**Comment by tomplus** [comment] 2020-01-15 21:00
Thanks. I wasn't aware of that the event loop can close before program ends.
It also explains this issue: https://github.com/tomplus/kubernetes_asyncio/issues/67
I hope it can bit only during closing an app.

**Comment by WouldYouKindly** [comment] 2020-01-16 08:27
Well, it depends on when you close the loop. If you close and open loops during the application runtime, you may run into issues.

Do you plan on fixing this? Or will you accept the PR? I'm not sure which parts are generated and which are hand-written though. Could you provide the command which is used to generate stubs?

**Comment by tomplus** [comment] 2020-01-21 21:13
This part is generated by openapi-generator - https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/python/asyncio/rest.mustache#L80

And to re-generate this library you can use this script:
https://github.com/tomplus/kubernetes_asyncio/blob/master/scripts/update-client.sh

Feel free to fix it if you want. I'll accept the PR and I can help with it too.

**Comment by tomplus** [comment] 2020-04-13 22:01
Hi @WouldYouKindly The issue is already fixed in 11.2.0. There are the context manager and the `close()` method to explicit close client connections.

**Closed by tomplus** 2020-04-13 22:01 UTC
